/* Password hashing for oper/link/die/restart logins.
 *
 * Ported from sekurircd/src/sekurircd/passwords.py -- same self-describing
 * format ("scrypt$<n>$<r>$<p>$<salt-hex>$<digest-hex>"), same OWASP-minimum
 * cost parameters (N=2^14, r=8, p=1, dklen=64), so hashes generated by the
 * Python daemon's `sekurircd --hash-password` keep verifying here unchanged.
 * Uses OpenSSL (EVP_PBE_scrypt / RAND_bytes / CRYPTO_memcmp) -- no hand-rolled
 * KDF or CSPRNG.
 */
#ifndef SEKURIRCD_CRYPTO_H
#define SEKURIRCD_CRYPTO_H

#include <stddef.h>

/* Hash `password`, writing the self-describing string into `out` (needs at
 * least 160 bytes: "scrypt$16384$8$1$" + 32 hex + "$" + 128 hex + NUL).
 * Returns 0 on success, -1 on an OpenSSL failure (out-of-memory or similar --
 * never expected in practice). */
int crypto_hash_password(const char *password, char *out, size_t outsz);

/* Constant-time verify `password` against a crypto_hash_password string.
 * Returns 1 if it matches, 0 otherwise -- including for a malformed/foreign
 * `stored` value, so a typo'd config entry fails closed instead of crashing. */
int crypto_verify_password(const char *password, const char *stored);

/* `count` random bytes, hex-encoded (lowercase) into `out` (needs at least
 * 2*count + 1 bytes). Used for host-cloak tokens. Aborts the process on
 * RAND_bytes failure (this daemon has no sane fallback for a broken CSPRNG). */
void crypto_random_hex(char *out, size_t outsz, int count);

#endif /* SEKURIRCD_CRYPTO_H */
